/** Text가 가질 수 있는 색상 Class 모음 객체 */
export const textColor = {
  transparent: "text-transparent",
  inherit: "text-inherit",
  primary: "text-primary",
  primaryInverse: "text-primary-inverse",
  primaryContainer: "text-primary-container",
  secondary: "text-secondary",
  secondaryContainer: "text-secondary-container",
  error: "text-error",
  errorContainer: "text-error-container",
  onSurface: "text-surface-on",
  onSurfaceInverse: "text-surface-on-inverse",
  onSurfaceVariant: "text-surface-on-variant",
  onSurfaceVariantInverse: "text-surface-on-variant-inverse",
  onPrimary: "text-primary-on",
  onPrimaryContainer: "text-primary-container-on",
  onSecondary: "text-secondary-on",
  onSecondaryContainer: "text-primary-container-on",
  onError: "text-error-on",
  onErrorContainer: "text-error-container-on",
};
